//! Account activity event stream (`GET /v2beta1/events/activities`).
//!
//! The same activities served as a snapshot by
//! [`TradingClient::get_account_activities`](crate::trading::TradingClient::get_account_activities)
//! are also pushed live over Server-Sent Events, in a richer envelope: every
//! event carries a ULID `event_id` plus a `details` object whose shape depends
//! on whether the activity is a trade execution or a non-trade booking.

use chrono::{DateTime, NaiveDate, Utc};
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use url::Url;

use crate::error::Result;
use crate::rest::Credentials;
use crate::stream::events::{EventStream, validate_replay_window};
use crate::trading::{ActivityType, OrderSide, OrderStatus};

const PAPER_BASE: &str = "https://paper-api.alpaca.markets";
const LIVE_BASE: &str = "https://api.alpaca.markets";
const ACTIVITIES_PATH: &str = "/v2beta1/events/activities";

/// How a trade activity event came about.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TradeExecutionType {
    /// A normal (partial or full) fill.
    Fill,
    /// A correction to a previously reported execution.
    TradeCorrect,
    /// A cancellation ("bust") of a previously reported execution.
    TradeBust,
    /// An execution type added by the API after this crate was released.
    #[serde(untagged)]
    Other(String),
}

/// `details` of a trade activity event — a fill, correction or bust.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradeActivityEventDetails {
    /// Id of the order that executed, as generated by Alpaca.
    pub order_id: String,
    /// Client-supplied order id, when the order carried one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub client_order_id: Option<String>,
    /// Side of the execution.
    pub side: OrderSide,
    /// Symbol that traded.
    pub symbol: String,
    /// Asset id; for options this is the option contract id.
    pub asset_id: String,
    /// CUSIP of the security, when known.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cusip: Option<String>,
    /// Quantity still unfilled on the order (`0` once it is fully filled).
    pub leaves_qty: Decimal,
    /// Total quantity filled on the order so far.
    pub cum_qty: Decimal,
    /// Status of the order after this execution.
    pub order_status: OrderStatus,
    /// Whether this is a fill, a correction or a bust.
    pub execution_type: TradeExecutionType,
    /// Commission collected from the account holder.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub commission: Option<Decimal>,
}

/// `details` of a non-trade activity event — a dividend, journal, fee,
/// transfer, corporate action, ...
///
/// The per-type fields differ for each of the ~36 non-trade activity types,
/// so only the two fields common to all of them are modeled; everything else
/// is preserved verbatim in [`extra`](Self::extra).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NonTradeActivityEventDetails {
    /// The date the activity was booked.
    pub system_date: NaiveDate,
    /// Groups activities that belong to the same underlying event.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
    /// Remaining type-specific fields (e.g. `entitled_qty` and `cash_payout`
    /// on a cash dividend, `parent_id` on a fee), as raw JSON.
    #[serde(flatten)]
    pub extra: std::collections::BTreeMap<String, serde_json::Value>,
}

/// The `details` payload of an [`ActivityEvent`].
///
/// The two families share no tag field, but their shapes are disjoint (only
/// trade details carry `order_id`, only non-trade details carry
/// `system_date`), so serde picks the variant structurally — the same
/// approach as [`AccountActivity`](crate::trading::AccountActivity).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ActivityEventDetails {
    /// A fill, correction or bust. Boxed to keep the enum small.
    Trade(Box<TradeActivityEventDetails>),
    /// A non-trade booking.
    NonTrade(NonTradeActivityEventDetails),
    /// A details shape this crate does not model, kept as raw JSON so an
    /// unexpected payload cannot break the stream.
    Other(serde_json::Value),
}

/// A single account activity pushed over the events stream.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivityEvent {
    /// Lexically sortable, monotonically increasing ULID identifying this
    /// emission. Use it as `since_id` (or the `Last-Event-Id` header) to
    /// resume the stream.
    pub event_id: String,
    /// When the streaming service emitted the event.
    pub at: DateTime<Utc>,
    /// The kind of activity.
    pub activity_type: ActivityType,
    /// A finer classification of `activity_type` (e.g. `CDIV` under `DIV`),
    /// when the API populates one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub activity_subtype: Option<String>,
    /// When the activity executed.
    pub executed_at: DateTime<Utc>,
    /// Status of the activity (e.g. `executed`, `correct`, `canceled`).
    pub status: String,
    /// The date the activity settled.
    pub settle_date: NaiveDate,
    /// ISO currency code of the amounts on this event.
    pub currency: String,
    /// Unique identifier of the activity itself: the execution id for trades,
    /// the transaction id otherwise.
    pub ref_id: String,
    /// Identifier of the activity this one corrects or cancels, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub previous_id: Option<String>,
    /// Net amount of money moved by the activity (positive or negative).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub net_amount: Option<Decimal>,
    /// Price of the security involved.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub price: Option<Decimal>,
    /// Quantity of the security involved.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub qty: Option<Decimal>,
    /// Conversion rate applied, for local-currency activities.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub swap_rate: Option<Decimal>,
    /// Currency conversion fee in basis points, for local-currency
    /// activities.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub swap_fee_bps: Option<Decimal>,
    /// Type-specific payload of the activity.
    pub details: ActivityEventDetails,
}

/// Query parameters for [`ActivityEventsClient::subscribe`].
///
/// Without a `since` or `since_id` the stream carries live events only. With
/// one of them, matching history is replayed first and the stream then
/// continues live; adding `until`/`until_id` closes the stream at that point
/// instead.
#[derive(Debug, Clone, Default, Serialize)]
pub struct ActivityEventsRequest {
    /// Replay events emitted at or after this time.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub since: Option<DateTime<Utc>>,
    /// Stop the stream after this time. Requires `since`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub until: Option<DateTime<Utc>>,
    /// Replay events with an `event_id` at or after this ULID. Mutually
    /// exclusive with `since`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub since_id: Option<String>,
    /// Stop the stream once this `event_id` has been delivered. Requires
    /// `since_id`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub until_id: Option<String>,
}

impl ActivityEventsRequest {
    /// Creates a request with no replay window: live events only.
    pub fn new() -> Self {
        Self::default()
    }

    /// Rejects the parameter combinations the endpoint refuses.
    pub(crate) fn validate(&self) -> Result<()> {
        validate_replay_window(
            self.since.is_some(),
            self.until.is_some(),
            self.since_id.is_some(),
            self.until_id.is_some(),
        )
    }
}

/// Client for the account activity event stream.
///
/// The endpoint is on the trading host and is still versioned `v2beta1`;
/// Alpaca plans to promote it to `/v2` and redirect the beta path.
pub struct ActivityEventsClient {
    base: Url,
    creds: Credentials,
}

impl ActivityEventsClient {
    /// Creates a new client. `paper: true` targets the paper trading
    /// environment.
    pub fn new(creds: Credentials, paper: bool) -> Result<Self> {
        let base = if paper { PAPER_BASE } else { LIVE_BASE };
        Self::with_base_url(creds, base)
    }

    /// Creates a new client targeting a custom base URL instead of the
    /// default Alpaca endpoint (parity with alpaca-py's `url_override`).
    pub fn with_base_url(creds: Credentials, base_url: &str) -> Result<Self> {
        Ok(Self {
            base: Url::parse(base_url)?,
            creds,
        })
    }

    /// `GET /v2beta1/events/activities` — opens the activity event stream.
    ///
    /// The returned [`EventStream`] yields one [`ActivityEvent`] per call to
    /// [`next`](EventStream::next) until the server closes the connection.
    pub async fn subscribe(
        &self,
        req: &ActivityEventsRequest,
    ) -> Result<EventStream<ActivityEvent>> {
        req.validate()?;
        EventStream::connect(&self.base, ACTIVITIES_PATH, req, &self.creds).await
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::Error;

    const TRADE_EVENT_JSON: &str = r#"{
        "event_id": "01J9RPMV5TKB8WX3M4F1KZ7QH2",
        "at": "2026-03-20T12:24:58.807230Z",
        "activity_type": "FILL",
        "executed_at": "2026-03-20T12:24:58.700000Z",
        "status": "executed",
        "settle_date": "2026-03-22",
        "currency": "USD",
        "ref_id": "33cbb614-bfc0-468b-b4d0-ccf08588ef77",
        "net_amount": "-1813.60",
        "price": "181.36",
        "qty": "10",
        "details": {
            "order_id": "bb2403bc-88ec-430b-b41c-f9ee80c8f0e1",
            "client_order_id": "my-order-1",
            "side": "buy",
            "symbol": "AAPL",
            "asset_id": "b0b6dd9d-8b9b-48a9-ba46-b9d54906e415",
            "leaves_qty": "0",
            "cum_qty": "10",
            "order_status": "filled",
            "execution_type": "fill",
            "commission": "0.01"
        }
    }"#;

    const NON_TRADE_EVENT_JSON: &str = r#"{
        "event_id": "01J9RQ5HNZQK7M3RDVJ8XBPCT1",
        "at": "2026-03-20T15:42:11.118274Z",
        "activity_type": "DIV",
        "activity_subtype": "CDIV",
        "executed_at": "2026-03-20T15:42:10.000000Z",
        "status": "executed",
        "settle_date": "2026-03-20",
        "currency": "USD",
        "ref_id": "f8489167-4e4b-431d-a0be-6017ae1cf08a",
        "net_amount": "0.07",
        "details": {
            "system_date": "2026-03-20",
            "group_id": "9ab15e44-569c-4c32-952c-b83ab7076549",
            "symbol": "JEPQ",
            "entitled_qty": "0.15905",
            "cash_payout": "0.07"
        }
    }"#;

    #[test]
    fn trade_event_round_trip() {
        let event: ActivityEvent = serde_json::from_str(TRADE_EVENT_JSON).unwrap();
        assert_eq!(event.event_id, "01J9RPMV5TKB8WX3M4F1KZ7QH2");
        assert_eq!(event.activity_type, ActivityType::Fill);
        assert_eq!(event.net_amount, Some(Decimal::new(-181360, 2)));
        let ActivityEventDetails::Trade(details) = &event.details else {
            panic!("expected trade details, got {:?}", event.details);
        };
        assert_eq!(details.symbol, "AAPL");
        assert_eq!(details.side, OrderSide::Buy);
        assert_eq!(details.order_status, OrderStatus::Filled);
        assert_eq!(details.execution_type, TradeExecutionType::Fill);
        assert_eq!(details.leaves_qty, Decimal::ZERO);
        assert_eq!(details.commission, Some(Decimal::new(1, 2)));

        let again: ActivityEvent =
            serde_json::from_str(&serde_json::to_string(&event).unwrap()).unwrap();
        assert_eq!(again.event_id, event.event_id);
        assert!(matches!(again.details, ActivityEventDetails::Trade(_)));
    }

    #[test]
    fn non_trade_event_keeps_type_specific_fields() {
        let event: ActivityEvent = serde_json::from_str(NON_TRADE_EVENT_JSON).unwrap();
        assert_eq!(event.activity_type, ActivityType::Div);
        assert_eq!(event.activity_subtype.as_deref(), Some("CDIV"));
        let ActivityEventDetails::NonTrade(details) = &event.details else {
            panic!("expected non-trade details, got {:?}", event.details);
        };
        assert_eq!(
            details.system_date,
            NaiveDate::from_ymd_opt(2026, 3, 20).unwrap()
        );
        assert_eq!(details.extra["symbol"], "JEPQ");
        assert_eq!(details.extra["cash_payout"], "0.07");
        // `group_id` is modeled, so it must not be duplicated into `extra`.
        assert!(!details.extra.contains_key("group_id"));

        let again: ActivityEvent =
            serde_json::from_str(&serde_json::to_string(&event).unwrap()).unwrap();
        let ActivityEventDetails::NonTrade(details) = &again.details else {
            panic!("expected non-trade details after round trip");
        };
        assert_eq!(details.extra["entitled_qty"], "0.15905");
    }

    #[test]
    fn unknown_activity_type_and_execution_type_survive() {
        let json = TRADE_EVENT_JSON.replace("\"FILL\"", "\"VOF\"").replace(
            "\"execution_type\": \"fill\"",
            "\"execution_type\": \"warp\"",
        );
        let event: ActivityEvent = serde_json::from_str(&json).unwrap();
        assert_eq!(event.activity_type, ActivityType::Other("VOF".to_string()));
        let ActivityEventDetails::Trade(details) = &event.details else {
            panic!("expected trade details");
        };
        assert_eq!(
            details.execution_type,
            TradeExecutionType::Other("warp".to_string())
        );
    }

    #[test]
    fn unmodeled_details_fall_back_to_raw_json() {
        let json = NON_TRADE_EVENT_JSON.replace("\"system_date\": \"2026-03-20\",", "");
        let event: ActivityEvent = serde_json::from_str(&json).unwrap();
        let ActivityEventDetails::Other(raw) = &event.details else {
            panic!("expected raw details, got {:?}", event.details);
        };
        assert_eq!(raw["symbol"], "JEPQ");
    }

    #[test]
    fn request_serializes_only_the_set_parameters() {
        let mut req = ActivityEventsRequest::new();
        assert_eq!(serde_json::to_value(&req).unwrap(), serde_json::json!({}));

        req.since_id = Some("01J9RPMV5TKB8WX3M4F1KZ7QH2".to_string());
        req.until_id = Some("01J9RVB6Y4ZK8M3N7QD2WX1RFP".to_string());
        assert_eq!(
            serde_json::to_value(&req).unwrap(),
            serde_json::json!({
                "since_id": "01J9RPMV5TKB8WX3M4F1KZ7QH2",
                "until_id": "01J9RVB6Y4ZK8M3N7QD2WX1RFP"
            })
        );
    }

    #[test]
    fn request_validation_rejects_bad_replay_windows() {
        let mut req = ActivityEventsRequest::new();
        req.until = Some(Utc::now());
        assert!(matches!(req.validate(), Err(Error::InvalidRequest(_))));

        let mut req = ActivityEventsRequest::new();
        req.since = Some(Utc::now());
        req.since_id = Some("01J9RPMV5TKB8WX3M4F1KZ7QH2".to_string());
        assert!(matches!(req.validate(), Err(Error::InvalidRequest(_))));

        let mut req = ActivityEventsRequest::new();
        req.since = Some(Utc::now());
        req.until = Some(Utc::now());
        assert!(req.validate().is_ok());
    }
}
